### ISSUE TITLE
Redirecting Alert to a Google Chat Room with Spaces in its Name.

### ISSUE THREAD

**Issue by Yagyansh** [mr-karan/calert#23]
Hi. I have been using CAlert quite actively. It's working like a charm, but for the Google Chat Rooms whose name has space in it, it fails. No alert is redirected to that chat. 
Is there any workaround for it? 

For eg. The redirection would work fine for the name - "ChatRoom", but would fail for "Chat Room".

**Comment by mr-karan** [comment]
The `room_name` parameter actually comes from AlertManager and in `cAlert` the config is just a simple mapping which takes the name from Alertmanager webhook payload (as seen [here](https://github.com/mr-karan/calert/blob/master/api.go#L85)) and does a key lookup with that name to fetch the webhook URL. Google Chat APIs does only care about the webhook URL so you can have spaces in the name of room.

The `room_name` parameter is something internal and you can't have space here because [TOML doesn't support spaces in keys](https://github.com/toml-lang/toml/issues/185). However this has no bearing with the actual room name (where you can have spaces).

Closing this as I don't see a reason for this to be changed.

**Comment by ahsan-raza** [comment]
So if there is a space in the room_name, it will work as is right? but its not happening and the gchat receiver doesn't get any notifications. Can you please tell me how can I make it work?

**Comment by mr-karan** [comment]
> So if there is a space in the room_name, it will work as is right

No, `room_name` can't have spaces.

**Comment by ahsan-raza** [comment]
So if my google chat room name have spaces, how can I make it push notifications or this is the limitations that room name must not have spaces.

**Comment by mr-karan** [comment]
`room_name` need not represent the actual room name that can have spaces. For example, the actual room name can be "My Room Name", but `room_name="my_room_name"` is all you would need to set in the config. The `room_name` is just an internal config, the webhook URL is used to post the payload, so spaces/no spaces in the actual room name doesn't matter.

**Comment by ahsan-raza** [comment]
Thanks man that really helped me out. Resolved my issue
