### ISSUE TITLE
HTTP request proxy config

### ISSUE THREAD

**Issue by weichanxiang** [mr-karan/calert#29]
Hello, 

Thanks for creating a great project! Is there any way to specify a **proxy setting** while sending the HTTPS request to google chat room? I'm using v1.2.1. 

I'm getting similar error as below which I think is due to network issue.`
`ERR: 2020/05/20 14:42:48 /home/karan/Projects/calert/main.go:44: Error while processing request: Post "https://chat.googleapis.com/v1/spaces/AAAAAAAA11/messages?key=mykeyhere&token=mytokenhere%3D": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by mr-karan** [comment]
Currently no. But I think if you set `HTTP_PROXY` env variable, Go will read this and use that: https://stackoverflow.com/a/14661978

I've not tried this myself, but maybe you can take a look.

**Comment by weichanxiang** [comment]
thank you for the details!
I'm using Docker and tried to set the container HTTP_PROXY but the error seems to be persisting. Will try to investigate further.

**Comment by dreamblack86** [comment]
I have exactly the same problem with us. I find the approach to solve it via the config file more convenient, because the proxy information refers only to the application itself and not to the environment.

I took care of the problem and made a small pull request. Maybe @mr-karan  will find my change suitable and incorporate it into the master branch. =)
#30

**Comment by mr-karan** [comment]
https://github.com/mr-karan/calert/pull/30

I'll do a release soon.
